apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-apiserver
  labels:
    app: vault-apiserver
spec:
  selector:
    matchLabels:
      app: vault-apiserver
  template:
    metadata:
      labels:
        app: vault-apiserver
    spec:
      containers:
      - name: vault-apiserver
        image: quay.io/raffaelespazzoli/vault-apiserver
        ports:
        - containerPort: 8443
        env: 
        - name: VAULT_ADDR
          value: http://vault.vault.svc:8200
        args: 
        - --tls-cert-file=/etc/serving-certs/tls.crt 
        - --tls-private-key-file=/etc/serving-certs/tls.key 
        - --secure-port=8443
        - --kubernetes-authorization-mount-path=auth/kubernetes
        # --v=4
        volumeMounts:
        - name: serving-certs
          mountPath: /etc/serving-certs
      volumes:
        - name: serving-certs
          secret:
            secretName: serving-certs
            defaultMode: 420        