apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: serving-certs
  labels:
    app: vault-apiserver
  name: vault-apiserver
spec:
  ports:
  - name: http
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: vault-apiserver
  sessionAffinity: None
  type: ClusterIP