# permissions for end users to edit policybindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policybinding-editor-role
rules:
- apiGroups:
  - vault.redhatcop.redhat.io
  resources:
  - policybindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.redhatcop.redhat.io
  resources:
  - policybindings/status
  verbs:
  - get
