# permissions for end users to view secretengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretengine-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - secretengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - secretengines/status
  verbs:
  - get
