# permissions for end users to edit secretengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretengine-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - secretengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - secretengines/status
  verbs:
  - get
